# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\MainWindow.ui'
#
# Created: Wed Jan 28 23:21:46 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 914)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1021, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.saveChangeButton = QtWidgets.QPushButton(self.tab)
        self.saveChangeButton.setGeometry(QtCore.QRect(410, 460, 115, 32))
        self.saveChangeButton.setObjectName("saveChangeButton")
        self.currentDeckView = QtWidgets.QListView(self.tab)
        self.currentDeckView.setGeometry(QtCore.QRect(285, 50, 240, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentDeckView.sizePolicy().hasHeightForWidth())
        self.currentDeckView.setSizePolicy(sizePolicy)
        self.currentDeckView.setObjectName("currentDeckView")
        self.allDecksLabel = QtWidgets.QLabel(self.tab)
        self.allDecksLabel.setGeometry(QtCore.QRect(545, 20, 59, 16))
        self.allDecksLabel.setObjectName("allDecksLabel")
        self.removeCardButton = QtWidgets.QPushButton(self.tab)
        self.removeCardButton.setGeometry(QtCore.QRect(285, 460, 115, 32))
        self.removeCardButton.setAutoDefault(False)
        self.removeCardButton.setDefault(False)
        self.removeCardButton.setFlat(False)
        self.removeCardButton.setObjectName("removeCardButton")
        self.searchLabel = QtWidgets.QLabel(self.tab)
        self.searchLabel.setGeometry(QtCore.QRect(25, 20, 59, 16))
        self.searchLabel.setObjectName("searchLabel")
        self.allDecksView = QtWidgets.QListView(self.tab)
        self.allDecksView.setGeometry(QtCore.QRect(545, 50, 240, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allDecksView.sizePolicy().hasHeightForWidth())
        self.allDecksView.setSizePolicy(sizePolicy)
        self.allDecksView.setObjectName("allDecksView")
        self.searchLineEdit = QtWidgets.QLineEdit(self.tab)
        self.searchLineEdit.setGeometry(QtCore.QRect(95, 20, 113, 21))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.addCardButton = QtWidgets.QPushButton(self.tab)
        self.addCardButton.setGeometry(QtCore.QRect(145, 460, 115, 32))
        self.addCardButton.setObjectName("addCardButton")
        self.newDeckButton = QtWidgets.QPushButton(self.tab)
        self.newDeckButton.setGeometry(QtCore.QRect(545, 460, 115, 32))
        self.newDeckButton.setObjectName("newDeckButton")
        self.removeDeckButton = QtWidgets.QPushButton(self.tab)
        self.removeDeckButton.setGeometry(QtCore.QRect(670, 460, 115, 32))
        self.removeDeckButton.setObjectName("removeDeckButton")
        self.currectDeckLabel = QtWidgets.QLabel(self.tab)
        self.currectDeckLabel.setGeometry(QtCore.QRect(285, 20, 111, 16))
        self.currectDeckLabel.setObjectName("currectDeckLabel")
        self.cardView = QtWidgets.QListView(self.tab)
        self.cardView.setGeometry(QtCore.QRect(25, 50, 240, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardView.sizePolicy().hasHeightForWidth())
        self.cardView.setSizePolicy(sizePolicy)
        self.cardView.setObjectName("cardView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveChangeButton.setText(_translate("MainWindow", "Save changes"))
        self.allDecksLabel.setText(_translate("MainWindow", "Decks"))
        self.removeCardButton.setText(_translate("MainWindow", "Remove card"))
        self.searchLabel.setText(_translate("MainWindow", "Search"))
        self.addCardButton.setText(_translate("MainWindow", "Add card"))
        self.newDeckButton.setText(_translate("MainWindow", "New deck"))
        self.removeDeckButton.setText(_translate("MainWindow", "Remove deck"))
        self.currectDeckLabel.setText(_translate("MainWindow", "Current deck"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

